/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniprojet_cadenas_ducher;

/**
 *
 * @author louis
 */
public class accueil extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(accueil.class.getName());

    /**
     * Creates new form accueil
     */
    public accueil() {
        initComponents();
    }
int difficulte;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messbienvenue = new javax.swing.JLabel();
        boutonjouer = new javax.swing.JButton();
        boutonquitter = new javax.swing.JButton();
        modefacile = new javax.swing.JButton();
        modedur = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        messbienvenue.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        messbienvenue.setText("Bienvenue dans le jeu du code");

        boutonjouer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boutonjouer.setText("Jouer");
        boutonjouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonjouerActionPerformed(evt);
            }
        });

        boutonquitter.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boutonquitter.setText("Quitter");
        boutonquitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonquitterActionPerformed(evt);
            }
        });

        modefacile.setText("facile");
        modefacile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modefacileActionPerformed(evt);
            }
        });

        modedur.setText("dur");
        modedur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modedurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(messbienvenue, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(37, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boutonjouer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boutonquitter)
                        .addGap(22, 22, 22))))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(modefacile)
                .addGap(40, 40, 40)
                .addComponent(modedur)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(messbienvenue, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modefacile)
                    .addComponent(modedur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutonjouer)
                    .addComponent(boutonquitter))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonjouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonjouerActionPerformed
        jeucadenas jeu = new jeucadenas(difficulte);
        jeu.setVisible(true);   
        this.dispose();
    }//GEN-LAST:event_boutonjouerActionPerformed

    private void boutonquitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonquitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_boutonquitterActionPerformed

    private void modefacileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modefacileActionPerformed
          difficulte = 8;
           boutonjouer.setEnabled(true);
    }//GEN-LAST:event_modefacileActionPerformed

    private void modedurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modedurActionPerformed
          difficulte = 5;
           boutonjouer.setEnabled(true);
    }//GEN-LAST:event_modedurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new accueil().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonjouer;
    private javax.swing.JButton boutonquitter;
    private javax.swing.JLabel messbienvenue;
    private javax.swing.JButton modedur;
    private javax.swing.JButton modefacile;
    // End of variables declaration//GEN-END:variables
}
