/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniprojet_cadenas_ducher;

/**
 *
 * @author louis
 */
public class jeucadenas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jeucadenas.class.getName());

    /**
     * Creates new form jeucadenas
     */
    public jeucadenas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        up_chif1 = new javax.swing.JButton();
        up_chif2 = new javax.swing.JButton();
        up_chif3 = new javax.swing.JButton();
        up_chif4 = new javax.swing.JButton();
        down_chif1 = new javax.swing.JButton();
        down_chif2 = new javax.swing.JButton();
        down_chif3 = new javax.swing.JButton();
        down_chif4 = new javax.swing.JButton();
        chif1 = new javax.swing.JLabel();
        chif2 = new javax.swing.JLabel();
        chif3 = new javax.swing.JLabel();
        chif4 = new javax.swing.JLabel();
        button_test = new javax.swing.JButton();
        text_trouvelecode = new javax.swing.JLabel();
        text_tentatives = new javax.swing.JLabel();
        text_retry = new javax.swing.JButton();
        text_score = new javax.swing.JLabel();
        text_chiffrecorrect = new javax.swing.JLabel();
        text_chiffrebas = new javax.swing.JLabel();
        text_chiffrehaut = new javax.swing.JLabel();
        text_nbcorrect = new javax.swing.JLabel();
        text_nbhaut = new javax.swing.JLabel();
        text_nbbas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        up_chif1.setText("/\\");
            getContentPane().add(up_chif1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 101, -1, -1));

            up_chif2.setText("/\\");
                up_chif2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        up_chif2ActionPerformed(evt);
                    }
                });
                getContentPane().add(up_chif2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 101, -1, -1));

                up_chif3.setText("/\\");
                    getContentPane().add(up_chif3, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 101, -1, -1));

                    up_chif4.setText("/\\");
                        getContentPane().add(up_chif4, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 101, -1, -1));

                        down_chif1.setText("\\/");
                        getContentPane().add(down_chif1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 230, -1, -1));

                        down_chif2.setText("\\/");
                        down_chif2.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chif2ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chif2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

                        down_chif3.setText("\\/");
                        down_chif3.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chif3ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chif3, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 230, -1, -1));

                        down_chif4.setText("\\/");
                        getContentPane().add(down_chif4, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 230, -1, -1));

                        chif1.setText("jLabel1");
                        getContentPane().add(chif1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 142, 66, 64));

                        chif2.setText("jLabel2");
                        getContentPane().add(chif2, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 142, 71, 64));

                        chif3.setText("jLabel3");
                        getContentPane().add(chif3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 142, 58, 64));

                        chif4.setText("jLabel4");
                        getContentPane().add(chif4, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 142, 67, 64));

                        button_test.setText("Tester");
                        button_test.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                button_testActionPerformed(evt);
                            }
                        });
                        getContentPane().add(button_test, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 179, -1, -1));

                        text_trouvelecode.setText("Trouve le bon code en moins de5 tentatives!");
                        getContentPane().add(text_trouvelecode, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 22, 265, -1));

                        text_tentatives.setText("Tentatives");
                        getContentPane().add(text_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 233, 55, -1));

                        text_retry.setText("Retry");
                        getContentPane().add(text_retry, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 378, -1, -1));

                        text_score.setText("jLabel3");
                        getContentPane().add(text_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 271, 55, 44));

                        text_chiffrecorrect.setText("nombre de chiffres corrects :");
                        getContentPane().add(text_chiffrecorrect, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 321, 168, -1));

                        text_chiffrebas.setText("nombre de chiffres trop bas:");
                        getContentPane().add(text_chiffrebas, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 381, 160, -1));

                        text_chiffrehaut.setText("nombre de chiffres trop hauts :");
                        getContentPane().add(text_chiffrehaut, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 350, 175, -1));

                        text_nbcorrect.setText("jLabel1");
                        getContentPane().add(text_nbcorrect, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 321, 37, -1));

                        text_nbhaut.setText("jLabel2");
                        getContentPane().add(text_nbhaut, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 350, 37, -1));

                        text_nbbas.setText("jLabel3");
                        getContentPane().add(text_nbbas, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 381, 37, -1));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void up_chif2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chif2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chif2ActionPerformed

    private void down_chif3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chif3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_down_chif3ActionPerformed

    private void button_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_testActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_testActionPerformed

    private void down_chif2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chif2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_down_chif2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jeucadenas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_test;
    private javax.swing.JLabel chif1;
    private javax.swing.JLabel chif2;
    private javax.swing.JLabel chif3;
    private javax.swing.JLabel chif4;
    private javax.swing.JButton down_chif1;
    private javax.swing.JButton down_chif2;
    private javax.swing.JButton down_chif3;
    private javax.swing.JButton down_chif4;
    private javax.swing.JLabel text_chiffrebas;
    private javax.swing.JLabel text_chiffrecorrect;
    private javax.swing.JLabel text_chiffrehaut;
    private javax.swing.JLabel text_nbbas;
    private javax.swing.JLabel text_nbcorrect;
    private javax.swing.JLabel text_nbhaut;
    private javax.swing.JButton text_retry;
    private javax.swing.JLabel text_score;
    private javax.swing.JLabel text_tentatives;
    private javax.swing.JLabel text_trouvelecode;
    private javax.swing.JButton up_chif1;
    private javax.swing.JButton up_chif2;
    private javax.swing.JButton up_chif3;
    private javax.swing.JButton up_chif4;
    // End of variables declaration//GEN-END:variables
}
