/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniprojet_cadenas_ducher;

/**
 *
 * @author louis
 */
public class jeucadenas extends javax.swing.JFrame {
    classjeu boncode = new classjeu();
    
    int valeur = 0;
    int valeur2=0;
    int valeur3=0;
    int valeur4=0;
    int exact=0;
    int tropHaut=0;
    int tropBas=0;
    int z=0;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jeucadenas.class.getName());
    private int c1;
    private int c2;
    private int c3;
    private int c4;
    int MAX_TRY=2 ; 
    /**
     * Creates new form jeucadenas
     */
    public jeucadenas(int par) {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        up_chif1 = new javax.swing.JButton();
        up_chif2 = new javax.swing.JButton();
        up_chif3 = new javax.swing.JButton();
        up_chif4 = new javax.swing.JButton();
        down_chif1 = new javax.swing.JButton();
        down_chif2 = new javax.swing.JButton();
        down_chif3 = new javax.swing.JButton();
        down_chif4 = new javax.swing.JButton();
        chif1 = new javax.swing.JLabel();
        chif2 = new javax.swing.JLabel();
        chif3 = new javax.swing.JLabel();
        chif4 = new javax.swing.JLabel();
        button_test = new javax.swing.JButton();
        text_trouvelecode = new javax.swing.JLabel();
        text_tentatives = new javax.swing.JLabel();
        text_retry = new javax.swing.JButton();
        text_score = new javax.swing.JLabel();
        text_chiffrecorrect = new javax.swing.JLabel();
        text_chiffrebas = new javax.swing.JLabel();
        text_chiffrehaut = new javax.swing.JLabel();
        text_nbcorrect = new javax.swing.JLabel();
        text_nbhaut = new javax.swing.JLabel();
        text_nbbas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        up_chif1.setText("/\\");
            up_chif1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    up_chif1ActionPerformed(evt);
                }
            });
            getContentPane().add(up_chif1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 101, -1, -1));

            up_chif2.setText("/\\");
                up_chif2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        up_chif2ActionPerformed(evt);
                    }
                });
                getContentPane().add(up_chif2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 101, -1, -1));

                up_chif3.setText("/\\");
                    up_chif3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            up_chif3ActionPerformed(evt);
                        }
                    });
                    getContentPane().add(up_chif3, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 101, -1, -1));

                    up_chif4.setText("/\\");
                        up_chif4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up_chif4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(up_chif4, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 101, -1, -1));

                        down_chif1.setText("\\/");
                        down_chif1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chif1ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chif1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 230, -1, -1));

                        down_chif2.setText("\\/");
                        down_chif2.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chif2ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chif2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

                        down_chif3.setText("\\/");
                        down_chif3.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chif3ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chif3, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 230, -1, -1));

                        down_chif4.setText("\\/");
                        down_chif4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chif4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chif4, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 230, -1, -1));

                        chif1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
                        chif1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        chif1.setText("   jLabel1");
                        chif1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
                        getContentPane().add(chif1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 142, 66, 64));

                        chif2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
                        chif2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        chif2.setText("    jLabel2");
                        chif2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
                        getContentPane().add(chif2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 71, 64));

                        chif3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
                        chif3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        chif3.setText("   jLabel3");
                        chif3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
                        getContentPane().add(chif3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 70, 64));

                        chif4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
                        chif4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        chif4.setText("   jLabel4");
                        chif4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
                        getContentPane().add(chif4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 67, 64));

                        button_test.setText("Tester");
                        button_test.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                button_testActionPerformed(evt);
                            }
                        });
                        getContentPane().add(button_test, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

                        text_trouvelecode.setText("Trouve le bon code en moins de 5 tentatives!");
                        getContentPane().add(text_trouvelecode, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 22, 265, -1));

                        text_tentatives.setText("Tentatives");
                        getContentPane().add(text_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 233, 55, -1));

                        text_retry.setText("Retry");
                        text_retry.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                text_retryActionPerformed(evt);
                            }
                        });
                        getContentPane().add(text_retry, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 378, -1, -1));

                        text_score.setText("0");
                        getContentPane().add(text_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 55, 44));

                        text_chiffrecorrect.setText("nombre de chiffres corrects :");
                        getContentPane().add(text_chiffrecorrect, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 321, 168, -1));

                        text_chiffrebas.setText("nombre de chiffres trop bas:");
                        getContentPane().add(text_chiffrebas, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 381, 160, -1));

                        text_chiffrehaut.setText("nombre de chiffres trop hauts :");
                        getContentPane().add(text_chiffrehaut, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 350, 175, -1));

                        text_nbcorrect.setText("0");
                        getContentPane().add(text_nbcorrect, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 321, 120, -1));

                        text_nbhaut.setText("0");
                        getContentPane().add(text_nbhaut, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 350, 110, -1));

                        text_nbbas.setText("0");
                        getContentPane().add(text_nbbas, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 381, 100, -1));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void up_chif2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chif2ActionPerformed
     valeur2 = valeur2 + 1;

    if(valeur2 > 9){
        valeur2 = 0;    }
chif2.setText(String.valueOf(valeur2)); 
                                 
    }//GEN-LAST:event_up_chif2ActionPerformed

    private void down_chif3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chif3ActionPerformed
        valeur3--;

    if(valeur3 < 0){
        valeur3 = 9;
    }
    chif3.setText(String.valueOf(valeur3));
    }//GEN-LAST:event_down_chif3ActionPerformed

    private void button_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_testActionPerformed



    
    int[] essai = {valeur, valeur2, valeur3, valeur4};
    int[] solution = boncode.solution;

    exact = 0;
    tropHaut = 0;
    tropBas = 0;

    for (int i = 0; i < 4; i++) {
        if (essai[i] == solution[i]) {
            exact++;
        } else if (essai[i] > solution[i]) {
            tropHaut++;
        } else {
            tropBas++;
        }
    }

    text_nbcorrect.setText("Exact : " + exact);
    text_nbhaut.setText("Trop hauts : " + tropHaut);
    text_nbbas.setText("Trop bas : " + tropBas);

    z++;
    text_score.setText(z + "/" + MAX_TRY);
    if (exact == 4) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Bravo ! Tu as trouvé le bon code !",
            "Réussite",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
        button_test.setEnabled(false);
        return;
    }

   
    if (z == MAX_TRY) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Vous avez échoué",
            "Fin de partie",
            javax.swing.JOptionPane.WARNING_MESSAGE
        );
        button_test.setEnabled(false);
    }
    }//GEN-LAST:event_button_testActionPerformed

    private void down_chif2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chif2ActionPerformed
        valeur2--;

    if(valeur2 < 0){
        valeur2 = 9;   }
chif2.setText(String.valueOf(valeur2));
  
    }//GEN-LAST:event_down_chif2ActionPerformed

    private void up_chif1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chif1ActionPerformed
    valeur = valeur + 1;

    if(valeur > 9){
        valeur = 0;
    }

    chif1.setText(String.valueOf(valeur)); 
    }//GEN-LAST:event_up_chif1ActionPerformed

    private void down_chif1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chif1ActionPerformed
   valeur--;

    if(valeur < 0){
        valeur = 9;
    }

    chif1.setText(String.valueOf(valeur));
    }//GEN-LAST:event_down_chif1ActionPerformed

    private void up_chif3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chif3ActionPerformed
        valeur3 = valeur3 + 1;

    if(valeur3 > 9){
        valeur3 = 0;
    }

    chif3.setText(String.valueOf(valeur3));
    }//GEN-LAST:event_up_chif3ActionPerformed

    private void down_chif4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chif4ActionPerformed
valeur4--;

    if(valeur4 < 0){
        valeur4 = 9;
    }

    chif4.setText(String.valueOf(valeur4));        // TODO add your handling code here:
    }//GEN-LAST:event_down_chif4ActionPerformed

    private void up_chif4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chif4ActionPerformed
       valeur4 = valeur4 + 1;

    if(valeur4 > 9){
        valeur4 = 0;
    }

    chif4.setText(String.valueOf(valeur4));
    }//GEN-LAST:event_up_chif4ActionPerformed

    private void text_retryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_retryActionPerformed

    text_score.setText("0/" + MAX_TRY);
    button_test.setEnabled(true); 

    exact = 0;
    tropHaut = 0;
    tropBas = 0;
    z=0;

    chif1.setText("0");
    chif2.setText("0");
    chif3.setText("0");
    chif4.setText("0");
   
    text_nbcorrect.setText("Exact : 0");
    text_nbhaut.setText("Trop hauts : 0");
    text_nbbas.setText("Trop bas : 0");

    text_score.setText("0");
    }//GEN-LAST:event_text_retryActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_test;
    private javax.swing.JLabel chif1;
    private javax.swing.JLabel chif2;
    private javax.swing.JLabel chif3;
    private javax.swing.JLabel chif4;
    private javax.swing.JButton down_chif1;
    private javax.swing.JButton down_chif2;
    private javax.swing.JButton down_chif3;
    private javax.swing.JButton down_chif4;
    private javax.swing.JLabel text_chiffrebas;
    private javax.swing.JLabel text_chiffrecorrect;
    private javax.swing.JLabel text_chiffrehaut;
    private javax.swing.JLabel text_nbbas;
    private javax.swing.JLabel text_nbcorrect;
    private javax.swing.JLabel text_nbhaut;
    private javax.swing.JButton text_retry;
    private javax.swing.JLabel text_score;
    private javax.swing.JLabel text_tentatives;
    private javax.swing.JLabel text_trouvelecode;
    private javax.swing.JButton up_chif1;
    private javax.swing.JButton up_chif2;
    private javax.swing.JButton up_chif3;
    private javax.swing.JButton up_chif4;
    // End of variables declaration//GEN-END:variables
}
